openapi: 3.1.0
info:
  title: Prompt Open API
  version: 1.0.0
  description: |-
    EasyPrompt 平台开放 API 文档
    
    包含 Prompt 列表、详情、创建等接口，支持 API Key 鉴权。
servers:
  - url: https://yourdomain.com
paths:
  /api/open/prompts:
    get:
      summary: 获取 Prompt 列表
      description: 支持关键词搜索、分页。
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: 关键词，模糊搜索标题和内容
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: 页码，默认1
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 20
          description: 每页数量，默认20
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  page:
                    type: integer
                  pageSize:
                    type: integer
                  prompts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Prompt'
              example:
                total: 2
                page: 1
                pageSize: 10
                prompts:
                  - id: cmciwwtcp0009kw2c1tscdeg
                    title: ChatGPT 快速入门
                    content: 如何高效使用ChatGPT...
    post:
      summary: 新增 Prompt（需鉴权）
      description: 需在 body 中传递 apikey 字段。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - apikey
              properties:
                title:
                  type: string
                  description: 标题
                content:
                  type: string
                  description: 内容
                apikey:
                  type: string
                  description: API Key
            example:
              title: ChatGPT 快速入门
              content: 如何高效使用ChatGPT...
              apikey: your_api_key
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prompt'
              example:
                id: cmciwwtcp0009kw2c1tscdeg
                title: ChatGPT 快速入门
                content: 如何高效使用ChatGPT...
  /api/open/prompts/{id}:
    get:
      summary: 获取单个 Prompt 详情
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Prompt ID
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prompt'
              example:
                id: cmciwwtcp0009kw2c1tscdeg
                title: ChatGPT 快速入门
                content: 如何高效使用ChatGPT...
components:
  schemas:
    Prompt:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string 